/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetofinalpoo;
//Leonardo Fasano RA:2564211

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author leona
 */
public class CadCarro extends javax.swing.JFrame {

    private Carro c1 = new Carro();
    private GerCar gc = GerCar.geraGerCar();
    private static CadCarro cpUnic;

    //Singleton
    public static CadCarro geraCadCarro() {
        if (cpUnic == null) {
            cpUnic = new CadCarro();
        }
        return cpUnic;
    }

    public CadCarro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCdCarro = new javax.swing.JLabel();
        lbMarc = new javax.swing.JLabel();
        lbMod = new javax.swing.JLabel();
        lbPreço = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMarc = new javax.swing.JTextField();
        txtMod = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        txtComb = new javax.swing.JTextField();
        txtAirb = new javax.swing.JTextField();
        btInserir = new javax.swing.JButton();
        btAtua = new javax.swing.JButton();
        btExcl = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCar = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        btConsulta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbCdCarro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbCdCarro.setText("CADASTRO DE CARRO ");

        lbMarc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbMarc.setText("MARCA");

        lbMod.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbMod.setText("MODELO");

        lbPreço.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbPreço.setText("PREÇO");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("COMBUSTIVEL ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("QUANTIDADE DE AIRBAGS");

        txtMarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcActionPerformed(evt);
            }
        });

        btInserir.setText("INSERIR DADOS");
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });

        btAtua.setText("ATUALIZAR");
        btAtua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtuaActionPerformed(evt);
            }
        });

        btExcl.setText("EXCLUIR");
        btExcl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExclActionPerformed(evt);
            }
        });

        tbCar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MARCA", "MODELO", "PRECO", "COMBUSTIVEL", "AIRBAGS", "PLACA"
            }
        ));
        tbCar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCar);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("PLACA");

        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });

        btConsulta.setText("CONSULTAR");
        btConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(lbPreço, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(txtMarc, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btInserir)
                                .addGap(18, 18, 18)
                                .addComponent(btAtua)
                                .addGap(18, 18, 18)
                                .addComponent(btExcl)
                                .addGap(18, 18, 18)
                                .addComponent(btConsulta))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtAirb, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(14, 14, 14)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lbMarc)
                                                .addComponent(lbMod))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtMod, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtComb))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(lbCdCarro)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbCdCarro)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMarc)
                    .addComponent(txtMarc, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMod))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPreço)
                    .addComponent(txtPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtComb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAirb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInserir)
                    .addComponent(btAtua)
                    .addComponent(btExcl)
                    .addComponent(btConsulta))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcActionPerformed

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed
        try {
            insCar();
            listTab();
            limpar();
        } catch (ModelogrdException erro) {
            JOptionPane.showMessageDialog(
                    null,
                    "Erro",
                    "Erro de tipo de dados",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btInserirActionPerformed

    private void btExclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExclActionPerformed
        excCarPlaca();
        listTab();
        limpar();
    }//GEN-LAST:event_btExclActionPerformed

    private void btAtuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtuaActionPerformed
        AtuCarPlaca();
        listTab();
        limpar();
    }//GEN-LAST:event_btAtuaActionPerformed

    private void btConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultaActionPerformed
        consCarPlaca();
        listTab();


    }//GEN-LAST:event_btConsultaActionPerformed

    private void tbCarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCarMouseClicked
        selectTab();
    }//GEN-LAST:event_tbCarMouseClicked

    public void selectTab() {

        String valLinTab = "";

        int posLin = tbCar.getSelectedRow();
        int col = 0;
        for (col = 0; col < tbCar.getColumnCount(); col++) {
            valLinTab += tbCar.getModel().getValueAt(posLin, col).toString();

            if (col + 1 < tbCar.getColumnCount()) {
                valLinTab += " - ";
            }
        }

        JOptionPane.showMessageDialog(
                null,
                "Conteudo: " + valLinTab,
                "VALORES DA LINHA --> " + col,
                1
        );
    }

    public void listTab() {
        DefaultTableModel modelo = (DefaultTableModel) tbCar.getModel();
        int posLin = 0;

        modelo.setRowCount(posLin);

        for (Carro carro : gc.getBdCar()) { //for each
            modelo.insertRow(posLin, new Object[]{carro.getMarca(), carro.getModelo(), carro.getPreco(), carro.getTipoCombustivel(), carro.getAirbags(), carro.getPlaca()});
            posLin++;
        }
    }

    public void insCar() throws ModelogrdException {
        try {
            Carro c1 = new Carro();

            c1.setMarca(txtMarc.getText());
            c1.setPlaca(Integer.valueOf(txtPlaca.getText()));

            c1.setModelo(txtMod.getText());
            c1.setPreco(Double.valueOf(txtPreco.getText()));

            c1.setTipoCombustivel(txtComb.getText());
            c1.setAirbags(Integer.valueOf(txtAirb.getText()));

            c1 = gc.insCar(c1);

            if (c1 != null) {
                JOptionPane.showMessageDialog(
                        null,
                        "Carro Cadastrado com Sucesso!",
                        "CADASTRO DE Carro",
                        1
                );
            } else {
                JOptionPane.showMessageDialog(
                        null,
                        "PLACA DUPLICADA",
                        "CADASTRO DE CARRO",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }//fim try
        catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(
                    null,
                    "Valor do Placa deve ser um inteiro",
                    "Erro de tipo de dados",
                    JOptionPane.ERROR_MESSAGE
            );

            txtPlaca.requestFocus();
        } catch (ModelogrdException erro) {
            JOptionPane.showMessageDialog(
                    null,
                    "Erro",
                    "Erro de tipo de dados",
                    JOptionPane.ERROR_MESSAGE
            );
            limpar();
        }

    }

    public void excCarPlaca() {
        c1 = new Carro();

        c1.setPlaca(Integer.parseInt(txtPlaca.getText()));

        c1 = gc.delCarPlaca(c1);

        if (c1 == null) {

            JOptionPane.showMessageDialog(
                    null,
                    "Carro excluido com sucesso!",
                    "EXCLUSÃO DE CARRO",
                    1
            );
            limpar();
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "NÃO EXISTE CARRO COM ESTA PlACA",
                    "EXCLUSÃO DE CARRO",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    public void AtuCarPlaca() {
        try {
            c1 = new Carro();

            c1.setPlaca(Integer.parseInt(txtPlaca.getText()));
            c1.setModelo(txtMod.getText());

            c1 = gc.atualizaCarPlaca(c1);

            if (c1 != null) {
                txtPlaca.setText(Integer.toString(c1.getPlaca()));

                JOptionPane.showMessageDialog(
                        null,
                        "Confira do dados!",
                        "ALTERAÇÃO DE PLACA",
                        1
                );
                limpar();
            } else {
                JOptionPane.showMessageDialog(
                        null,
                        "NÃO EXISTE CARRO COM ESTA PLACA",
                        "ALTERAÇÃO DE CARRO",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        } catch (ModelogrdException erro) {
            JOptionPane.showMessageDialog(
                    null,
                    "Insira algum Dado",
                    "Erro de tipo de dados",
                    JOptionPane.ERROR_MESSAGE
            );
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(
                    null,
                    "Insira algum Dado",
                    "Erro de tipo de dados",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    public void consCarPlaca() {
        c1 = new Carro();

        c1.setPlaca(Integer.parseInt(txtPlaca.getText()));

        c1 = gc.consCarPlaca(c1);

        if (c1 != null) {

            txtMarc.setText(c1.getMarca());
            txtPreco.setText(String.valueOf(c1.getPreco()));
            txtMod.setText(c1.getModelo());
            txtComb.setText(c1.getTipoCombustivel());
            txtAirb.setText(Integer.toString(c1.getAirbags()));
            txtPlaca.setText(Integer.toString(c1.getPlaca()));

            JOptionPane.showMessageDialog(
                    null,
                    "Placa encontradas com sucesso! - Verifique os dados",
                    "CONSULTA DE PLACA",
                    1
            );
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "nÃO EXISTE CARRO COM ESTA PLACA",
                    "CONSULTA DE PLACA",
                    JOptionPane.ERROR_MESSAGE
            );
        }
        limpar();
    }

    public void limpar() {
        txtPlaca.setText("");
        txtMarc.setText("");
        txtPreco.setText("");
        txtMod.setText("");
        txtComb.setText("");
        txtAirb.setText("");
        txtPlaca.requestFocus();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtua;
    private javax.swing.JButton btConsulta;
    private javax.swing.JButton btExcl;
    private javax.swing.JButton btInserir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCdCarro;
    private javax.swing.JLabel lbMarc;
    private javax.swing.JLabel lbMod;
    private javax.swing.JLabel lbPreço;
    private javax.swing.JTable tbCar;
    private javax.swing.JTextField txtAirb;
    private javax.swing.JTextField txtComb;
    private javax.swing.JTextField txtMarc;
    private javax.swing.JTextField txtMod;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
